# Generated by Django 4.0.3 on 2022-03-09 01:11

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('orderType', models.IntegerField(choices=[(1, 'MARKET'), (2, 'LIMIT')], default=orders.models.OrderTypes['MARKET'])),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
    ]
