# Generated by Django 4.0.3 on 2022-03-23 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderType', models.CharField(choices=[('MARKET', 'MARKET'), ('LIMIT', 'LIMIT')], default=orders.models.OrderTypes['MARKET'], max_length=255)),
                ('orderDirection', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default=orders.models.OrderDirections['BUY'], max_length=255)),
                ('orderStatus', models.CharField(choices=[('PENDING', 'PENDING'), ('EXECUTED', 'EXECUTED')], default=orders.models.OrderStatus['PENDING'], max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('dynamicQuantity', models.IntegerField(default=1)),
                ('limitPrice', models.DecimalField(blank=True, decimal_places=3, max_digits=16)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updatedAt', '-createdAt'],
            },
        ),
    ]
