# Generated by Django 4.0.3 on 2022-03-23 20:44

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('EXECUTED', 'EXECUTED'), ('PARTIAL', 'PARTIAL')], default=orders.models.OrderStatus['PENDING'], max_length=255),
        ),
    ]
