# Generated by Django 4.0.3 on 2022-03-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-updatedAt', '-createdAt', '-orderId']},
        ),
        migrations.AddField(
            model_name='order',
            name='updatedAt',
            field=models.DateField(auto_now=True),
        ),
    ]
