# Generated by Django 4.0.3 on 2022-03-10 00:03

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_order_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderDirection',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default=orders.models.OrderDirections['BUY'], max_length=255),
        ),
    ]
