# Generated by Django 4.0.3 on 2022-03-10 00:40

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_orderdirection'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderType',
            field=models.CharField(choices=[('MARKET', 'MARKET'), ('SELL', 'LIMIT')], default=orders.models.OrderTypes['MARKET'], max_length=255),
        ),
    ]
