# Generated by Django 4.0.3 on 2022-03-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
