# Generated by Django 4.0.3 on 2022-03-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='lastTradedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
